spring:
  datasource:
    url: jdbc:mysql://test1.chx4mcftzr4f.us-west-1.rds.amazonaws.com:3306/movie
    username: admin
    password: mypassword
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
